config/routes.rb
MenuMeister::Application.routes.draw do

  resources :meals
  resources :foods

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/logoutsdjfkldsjfklsdjfldsfskdlfjlk', :to => 'sessions#destroy', :as => :logout

  root :to => 'main#index'
end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :calories, :name

  validates_presence_of :name
  validates_numericality_of :calories, :allow_nil => false

  belongs_to :user
end

app/models/food_meal.rb
class FoodMeal < ActiveRecord::Base
  attr_accessible :food_id, :meal_id

  belongs_to :food
  belongs_to :meal
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  attr_accessible :description, :name, :food_ids

  validates_presence_of :name, :description

  has_many :foods, :through => :food_meals
  has_many :food_meals

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :facebook_id, :name

  scope :admin, where(:is_admin => true)

  has_many :meals
  has_many :foods

  def options_for_foods
    if is_admin
      Food.joins(:user).
        where("users.is_admin = ? ", true)
    else
      Food.joins(:user).
        where("users.is_admin = ? or users.id = ?", true, id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @user ||= User.find(session[:user_id])
  rescue ActiveRecord::RecordNotFound
  end

  def current_user=(user)
    session[:user_id] = user.try(:id)
  end

  helper_method :current_user
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_filter :authenticate_user

  def authenticate_user
    unless current_user
      redirect_to "/", :notice => "Please log in"
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < AuthenticatedController
  inherit_resources

  protected
  def begin_of_association_chain
    current_user
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/meals_controller.rb
class MealsController < AuthenticatedController
  inherit_resources

  protected
  def begin_of_association_chain
    current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_by_facebook_id(auth_hash["uid"].to_i)
    @user.update_attribute(:email, auth_hash["info"]["email"])

    self.current_user = @user
    redirect_to '/', :notice => "You're logged in"
  end

  def destroy
    self.current_user = nil
    redirect_to '/', :notice => "You're logged out"
  end

  protected
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_form.html.erb
<%= semantic_form_for(@food) do |f| %>
  <%= f.input :name %>
  <%= f.input :calories, :as => :string %>

  <%= f.actions do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit</h1>

<%= render :partial => "form" %>

app/views/foods/index.html.erb
<p>
  <ul>
  <% @foods.each do |food| %>
    <li><%= link_to food.name, food %></li>
  <% end %>
  </ul>
</p>

<p>
  <%= link_to "Create new food", new_food_path %>
</p>

app/views/foods/new.html.erb
<h1>New</h1>

<%= render :partial => "form" %>

app/views/foods/show.html.erb
<h2><%= @food.name %></h2>
<p>Calories: <%= @food.calories %></p>

<ul>
  <li><%= link_to "Index", foods_path %></li>
  <li><%= link_to "Edit", edit_food_path(@food) %></li>
  <li><%= link_to "Destroy", food_path(@food), 
        :method => :delete, 
        :data => { :confirm => "Are you sure?" } 
      %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MenuMeister</title>
  <%= stylesheet_link_tag    "application", "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">
        Menu Meister
      </a>

      <ul class="nav pull-right">
        <li class="active">
          <% unless current_user %>
            <%= link_to "Log in With Facebook", "/auth/facebook" %>
          <% else %>
            Welcome, <%= current_user.email %>, 
              <%= link_to "Log out", logout_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <% if flash[:notice] %>
    <div class="alert">
      <button class="close" data-dismiss="alert">×</button>
      <strong><%= flash[:notice] %></strong>
    </div>
  <% end %>

  <%= yield %>

  <ul>
    <li><%= link_to "Meals", meals_path %></li>
    <li><%= link_to "Foods", foods_path %></li>
  </ul>
</div>

</body>
</html>

app/views/main/index.html.erb
Welcome to Menu Meister...

app/views/meals/index.html.erb
<p>
  <ul>
  <% @meals.each do |meal| %>
    <li><%= link_to meal.name, meal %></li>
  <% end %>
  </ul>
</p>

<p>
  <%= link_to "Create new meal", new_meal_path %>
</p>

app/views/meals/new.html.erb
<%= semantic_form_for(@meal) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :foods, :collection => current_user.options_for_foods %>

  <%= f.actions do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/meals/show.html.erb
<h2><%= @meal.name %></h2>

<p><%= @meal.description %></p>

<h3>Calorie Count: <%= @meal.foods.sum(:calories) %></h3>

<ul>
  <% @meal.foods.each do |food| %>
    <li><%= food.name %></li>
  <% end %>
</ul>

<ul>
  <li><%= link_to "My Meals", meals_path %></li>
  <li><%= link_to "Destroy", meal_path(@meal), :method => :delete, :data => { :confirm => "Are you sure?" } %></li>
</ul>